"""Add merchant_request_id and checkout_request_id to Payment model

Revision ID: 5e6417e6d81c
Revises: d63ea1e439fa
Create Date: 2025-06-27 16:16:08.829311

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils # Ensure this is imported
# Import Enums from your models file
from app.models import UserRole, BookingStatus, PaymentStatus


# revision identifiers, used by Alembic.
revision = '5e6417e6d81c'
down_revision = 'd63ea1e439fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255), # This might be what Alembic sees if previous state wasn't perfectly ChoiceType
               type_=sqlalchemy_utils.types.choice.ChoiceType(BookingStatus), # Use Enum class
               existing_nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255), # This might be what Alembic sees
               type_=sqlalchemy_utils.types.choice.ChoiceType(PaymentStatus), # Use Enum class
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_payments_checkout_request_id'), ['checkout_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_merchant_request_id'), ['merchant_request_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=255), # This might be what Alembic sees
               type_=sqlalchemy_utils.types.choice.ChoiceType(UserRole), # Use Enum class
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sqlalchemy_utils.types.choice.ChoiceType(UserRole), # Use Enum class
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_merchant_request_id'))
        batch_op.drop_index(batch_op.f('ix_payments_checkout_request_id'))
        batch_op.alter_column('status',
               existing_type=sqlalchemy_utils.types.choice.ChoiceType(PaymentStatus), # Use Enum class
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('checkout_request_id')
        batch_op.drop_column('merchant_request_id')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sqlalchemy_utils.types.choice.ChoiceType(BookingStatus), # Use Enum class
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
